[package]
name = "saddle-animation-spritesheet-example-character-animation"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy.workspace = true
saddle-animation-spritesheet.workspace = true
saddle-animation-spritesheet-example-support = { path = "../support" }

[lints]
workspace = true
