[package]
name = "saddle-animation-spritesheet-example-crowd-variation"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = "0.18"
saddle-animation-spritesheet = { path = "../.." }
saddle-animation-spritesheet-example-support = { path = "../support" }
saddle-pane = { git = "https://github.com/julien-blanchon/saddle-pane" }

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
nonstandard_macro_braces = "warn"
