[package]
name = "saddle-animation-spritesheet-example-basic"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = "0.18"
saddle-animation-spritesheet = { path = "../.." }
saddle-animation-spritesheet-example-support = { path = "../support" }

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
nonstandard_macro_braces = "warn"
